"""follower counter

Revision ID: 1e74d4a16753
Revises: 8ca31bcc2729
Create Date: 2024-03-13 02:38:42.574697+11:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e74d4a16753'
down_revision = '8ca31bcc2729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
