"""removed embedding

Revision ID: a38855a97e57
Revises: 2fdc410931df
Create Date: 2024-03-13 04:49:09.411312+11:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38855a97e57'
down_revision = '2fdc410931df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
