"""added embedding

Revision ID: e1cf3a02b4d0
Revises: 3cd09210f663
Create Date: 2024-03-13 04:53:53.471921+11:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cf3a02b4d0'
down_revision = '3cd09210f663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('embedding', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'embedding')
    # ### end Alembic commands ###
